### ISSUE TITLE
Practica 1 modelo de Negocios

### ISSUE THREAD

**Issue by YaelStO** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipo-jdgras#2]
[Practica num.1 modelo de negocios.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipo-jdgras/files/12861423/Practica.num.1.modelo.de.negocios.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by Julissamigdalia** [comment]
18/20

**Comment by josealfredo79** [comment]
Revisado...
